apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-pflidigs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-pflidigs:52334870bd8975b2bee6b498b598286bacd05802@sha256:a1db045d2106429eb73dee927437b2d73f0bd0e9dd0bf6c22693c49445bfb690
          name: container-image
